# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FtpServer.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from functools import partial
from pyftpdlib.authorizers import DummyAuthorizer
from pyftpdlib.handlers import FTPHandler,ThrottledDTPHandler
from pyftpdlib.servers import FTPServer
import threading
from multiprocessing import Process
import configparser
import logging
import os,sys
import Ftp_Server
import utils
thread_ftp = Ftp_Server.FTP_server()
thread_ftp.setDaemon(True)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(510, 404)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(90, 130, 241, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(9, 193, 30, 16))
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(9, 52, 66, 16))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(9, 124, 18, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(89, 193, 241, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(180, 406, 110, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(170, 50, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(90, 50, 71, 21))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(9, 262, 78, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 260, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 300, 84, 16))
        self.label_6.setObjectName("label_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(100, 300, 75, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(190, 300, 241, 20))
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(190, 260, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 510, 21))
        self.menubar.setObjectName("menubar")
        self.menuFTP_Server = QtWidgets.QMenu(self.menubar)
        self.menuFTP_Server.setObjectName("menuFTP_Server")
        self.menuAdvaced = QtWidgets.QMenu(self.menubar)
        self.menuAdvaced.setObjectName("menuAdvaced")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFTP_Server.menuAction())
        self.menubar.addAction(self.menuAdvaced.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setText(_translate("MainWindow", "127.0.0.1"))
        self.label_4.setText(_translate("MainWindow", "端口:"))
        self.label.setText(_translate("MainWindow", "FTP_SERVER:"))
        self.label_3.setText(_translate("MainWindow", "IP:"))
        self.lineEdit_2.setText(_translate("MainWindow", "21"))
        self.lineEdit_4.setText(_translate("MainWindow", "100"))
        self.pushButton_5.setText(_translate("MainWindow", "OFF"))
        self.pushButton.setText(_translate("MainWindow", "ON"))
        self.label_2.setText(_translate("MainWindow", "匿名访问开关:"))
        self.pushButton_2.setText(_translate("MainWindow", "ON"))
        self.label_6.setText(_translate("MainWindow", "匿名访问路径："))
        self.pushButton_7.setText(_translate("MainWindow", "选择文件.."))
        self.pushButton_3.setText(_translate("MainWindow", "OFF"))
        self.menuFTP_Server.setTitle(_translate("MainWindow", "FTP_Server"))
        self.menuAdvaced.setTitle(_translate("MainWindow", "Advaced"))
    def showDialog(self):
        vbox=QtWidgets.QVBoxLayout()
        hbox = QtWidgets.QHBoxLayout()
        panel = QtWidgets.QLabel()
        panel.setText("端口被占用，请修改端口号或尝试重启程序")
        self.dialog = QtWidgets.QDialog()
        self.dialog.resize(300,100)
        self.dialog.setWindowTitle("提示信息！")
        vbox.addWidget(panel)
        vbox.addLayout(hbox)
        self.dialog.setLayout(vbox)
        self.dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        self.dialog.exec_()

def setstatus(ui,server_status,anon_status):
    if server_status == True:
        ui.pushButton.setEnabled(False)
        ui.pushButton_5.setEnabled(True)
        ui.pushButton_2.setEnabled(False)
        ui.pushButton_3.setEnabled(False)
        ui.pushButton_7.setEnabled(False)
        ui.lineEdit.setEnabled(False)
        ui .lineEdit_2.setEnabled(False)
        ui.lineEdit_3.setEnabled(False)
        ui.lineEdit_4.setEnabled(False)
    else:
        ui.pushButton.setEnabled(True)
        ui.pushButton_5.setEnabled(False)
        if anon_status == True:
            ui.pushButton_2.setEnabled(False)
            ui.pushButton_3.setEnabled(True)
        else:
            ui.pushButton_2.setEnabled(True)
            ui.pushButton_3.setEnabled(False)
        ui.pushButton_7.setEnabled(True)
        ui.lineEdit.setEnabled(True)
        ui.lineEdit_2.setEnabled(True)
        ui.lineEdit_3.setEnabled(True)
        ui.lineEdit_4.setEnabled(True)

def makeconnect(thread_ftp,ui):
    setstatus(ui,True,True)
    thread_ftp.setup()
    thread_ftp.startServer()
    print("ftp_server starting up")

def makeclose(thread_ftp,ui):
    utils.stop_thread(thread_ftp)
    thread_ftp.sleep()
    setstatus(ui,False,True)
    print("ftp_server close up")
def connect(ui):
    ui.pushButton.clicked.connect(partial(makeconnect,thread_ftp,ui))
    ui.pushButton_5.clicked.connect(partial(makeclose,thread_ftp,ui))


if __name__ == "__main__":
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    connect(ui)
    thread_ftp.start()
    MainWindow.show()    
    sys.exit(app.exec_())